intents:
  - HerokuStatus
  - HerokuBestCSA

utterances:
  HerokuStatus:
    - what is the status
    - what is the status of the platform
  HerokuBestCSA:
    - who is the best Customer Solutions Architect
