intents:
  - HerokuStatus
  - HerokuBestCSA
  - HerokuInfo:
      Concept: LIST_OF_CONCEPTS

utterances:
  HerokuStatus:
    - what is the status
    - what is the status of the platform
  HerokuBestCSA:
    - who is the best Customer Solutions Architect

slots:
    LIST_OF_CONCEPTS:
        - Dyno
        - Add-on
        - Connect
        - Private Space
        - App
        - Pipeline
