intents:
  - HerokuStatus
  - HerokuInfo

utterances:
  HerokuStatus:
    - what is the status
    - what is the status of the platform
  HerokuInfo:
    - who is the best Customer Solutions Architect
